name: Run tests

on:
  push:
  pull_request:

jobs:
  run-tests-ce:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.owner.login != 'tarantool'
    strategy:
      matrix:
        tarantool-version: ["1.10", "2.8"]
      fail-fast: false
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: ${{ matrix.tarantool-version }}

      - name: Install dependencies
        run: make .rocks

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test
